title: Idolm@ster Starlit Season Fan Translation
description: This is the homepage for the English Fan Translation for Idolm@ster Starlit Season
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman